apiVersion: v1
kind: Service
metadata:
  name: ryurulznginx
  labels:
    app: ryurulznginx
spec:
  ports:
  - port: 80
    name: ryurulznginx
  clusterIP: None
  selector:
    app: nryurulznginx
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: ryurulznginx
spec:
  serviceName: "ryurulznginx"
  replicas: 2
  selector:
    matchLabels:
      app: ryurulznginx
  template:
    metadata:
      labels:
        app: ryurulznginx
    spec:
      containers:
      - name: ryurulznginx
        image: registry.k8s.io/nginx-slim:0.8
        ports:
        - containerPort: 80
          name: ryurulznginx
        volumeMounts:
        - name: www
          mountPath: /usr/share/nginx/html
  volumeClaimTemplates:
  - metadata:
      name: www
    spec:
      accessModes: 
      - ReadWriteOnce
      resources:
        requests:
          storage: 1Gi
